defaults :
  - modulus_default
  - arch:
      - fully_connected
  - optimizer: adam
  - loss: sum
training:
  rec_monitor_freq: 200
  rec_validation_freq: 200
  max_steps: 200
optimizer:
  lr: 1e-4
amp:
  enabled: false
  dtype: float32
save_filetypes: np
