defaults :
  - modulus_default
  - arch:
      - fully_connected
  - optimizer: adam
  - loss: sum
training:
  rec_monitor_freq: 20000
  rec_validation_freq: 20000
  max_steps: 20000
  print_stats_freq: 1000
  grad_clip_max_norm: 100
  monitor_grad_clip: false
optimizer:
  lr: 1e-3
amp:
  enabled: false
  dtype: float32
save_filetypes: np
